import { existsSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { ISSUE_GROUPS } from "$lib/features/diagnosis";
import drillsJson from "../data/drills.json";
import { InvalidDrillError, parseDrillFile } from "../schema";

describe("shipped drill catalog", () => {
  const file = parseDrillFile(drillsJson);

  it("contains 12 valid drills with unique ids and slugs", () => {
    expect(file.drills).toHaveLength(12);
    expect(new Set(file.drills.map((d) => d.id)).size).toBe(12);
    expect(new Set(file.drills.map((d) => d.slug)).size).toBe(12);
  });

  it("covers every issue group with at least one drill", () => {
    const covered = new Set(file.drills.flatMap((d) => d.issueGroups));
    for (const group of ISSUE_GROUPS) {
      expect(covered, `no drill covers ${group}`).toContain(group);
    }
  });

  it("flags all shipped drills as placeholder content", () => {
    for (const d of file.drills) {
      expect(d.isPlaceholder).toBe(true);
      expect(d.videoUri).toBe("/drills/placeholder.webm");
      expect(d.thumbnailUri).toBe("/drills/placeholder-thumb.svg");
    }
  });

  it("spans all three difficulty levels", () => {
    const levels = new Set(file.drills.map((d) => d.difficulty));
    expect(levels).toEqual(new Set([1, 2, 3]));
  });

  it("references media assets that exist in static/", () => {
    // Generated by scripts/make-placeholder-drill-video.ts.
    const staticDir = fileURLToPath(
      new URL("../../../../../static", import.meta.url),
    );
    expect(existsSync(join(staticDir, "drills", "placeholder.webm"))).toBe(
      true,
    );
    expect(existsSync(join(staticDir, "drills", "placeholder-thumb.svg"))).toBe(
      true,
    );
  });
});

describe("drill schema", () => {
  const valid = parseDrillFile(drillsJson).drills[0]!;

  it("rejects unknown metrics, groups, and bad difficulty", () => {
    const cases: Record<string, unknown>[] = [
      { ...valid, focusMetrics: ["notAMetric"] },
      { ...valid, issueGroups: ["not-a-group"] },
      { ...valid, difficulty: 4 },
      { ...valid, coachingPoints: ["only one"] },
      { ...valid, slug: "Has Spaces" },
    ];
    for (const drill of cases) {
      expect(() => parseDrillFile({ version: 1, drills: [drill] })).toThrow(
        InvalidDrillError,
      );
    }
  });
});
